name: 'PR Issue Link'
description: An opinionated GitHub Action that checks for issues mentioned in a PR and optionally links them.
inputs:
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  prNumber:
    description: 'The PR number that triggered the workflow'
  issueNumbers:
    description: 'The issue number(s) mentioned in the PR'
runs:
  using: 'node18'
  main: 'dist/index.cjs'
